
// AUTO GENERATED BY MODWIG
function loadMods(api) {
for (var key in api) {
    var toRun = key + ' = api["' + key + '"]'
    println(toRun)
    eval(toRun)
}
        
// exclusiveArm.bitwig.js
// 
// 
// 
//
// mod.description = 'Ensures only one track can be armed at any one time'
// mod.category = 'global'

tracks.forEach((t, i) => {
    t.arm().addValueObserver(armed => {
        if (armed) {
            // Unarm all other tracks
            tracks.forEach((t, i2) => {
                if (i !== i2) {
                    t.arm().set(false);
                }
            })
        }
    })
})
                        
}